-- Find the total revenue generated by Atliqo each month.
SELECT TO_CHAR(date,'MONTH'), SUM(atliqo_revenue_crores) AS total_revenue_crores
FROM fact_atliqo_metrics
GROUP BY date
ORDER BY date;

-- What is the total number of active and unsubscribed users per month?
SELECT TO_CHAR(date,'MONTH'),
       SUM(active_users_lakhs) AS total_active_users_lakhs,
       SUM(unsubscribed_users_lakhs) AS total_unsubscribed_users_lakhs
FROM fact_atliqo_metrics
GROUP BY date
ORDER BY date;

-- Get the monthly market share % of Atliqo in each city.
SELECT city_code, ms_pct
FROM fact_market_share
WHERE company = 'Atliqo';

-- 